# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI 2

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  Run-npm-on-Ubuntu:
    name: Run npm on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm help

      - uses: actions/checkout@v3
      - name: Set up Elixir
        uses: erlef/setup-beam@988e02bfe678367a02564f65ca2e37726dc0268f
        with:
          elixir-version: '1.12.3' # Define the elixir version [required]
          otp-version: '24.1' # Define the OTP version [required]
      # - name: Restore dependencies cache
      #   uses: actions/cache@v3
      #   with:
      #     path: deps
      #     key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
      #     restore-keys: ${{ runner.os }}-mix-
      - name: Install dependencies
        run: mix deps.get
      # - name: Run tests
      #   run: mix test
