# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    name: Build and test

    strategy:
      matrix:
        os: [ubuntu20]
        elixir: [1.14.4]
        otp: [25.2.3]

    env:
      OTP_VERSION: ${{ matrix.otp }}
      ELIXIR_VERSION: ${{ matrix.elixir }}
      ImageOS: ubuntu20

    runs-on: ${{ matrix.os }}

    services:
      db:
        image: "mysql:8.0.33"
        ports: ["3306:3306"]
        env:
          MYSQL_ROOT_PASSWORD: mysql

    steps:    
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-deps
        with:
          path: deps
          key: ${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('**/mix.lock') }}

      - name: Set up Elixir
        uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          version-type: strict
      - name: Install dependencies
        run: mix deps.get

      - name: Check unused dependencies
        run: mix deps.unlock --check-unused

      - name: Compile code
        run: mix compile --warnings-as-errors --all-warnings

      - name: Run format
        run: mix format --check-formatted

      - name: Cache build 
        uses: actions/cache@v3
        id: cache-build
        with:
          path: _build/test
          key: ${{ matrix.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-mix-${{ hashFiles('mix.lock', 'mix.exs', 'config/*.exs') }}

      - name: Compile code
        run: mix compile --warnings-as-errors --all-warnings

      - name: Run Credo
        run: mix credo --strict

      - name: Create database
        run: mix ecto.create
        env:
          MIX_ENV: test
      
      - name: Run migrations
        run: mix ecto.migrate
        env:
          MIX_ENV: test

      - name: Run tests
        run: mix coveralls.lcov --warnings-as-errors | sed -e ':a' -e 'N' -e '$!ba' -e 's/\(\(WARNING:\ Deleting data for module\|Analysis includes data from imported files\)[^]]*]\n\)//g'; exit ${PIPESTATUS[0]}
        env:
          MIX_ENV: test
